name: flutter_meedu_videoplayer
description: A crossplatfrom video player.
version: 2.0.5
homepage: "https://github.com/zezo357/flutter_meedu_videoplayer"
environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  volume_controller: ^2.0.3
  video_player: ^2.3.0
  auto_orientation: ^2.2.1
  screen_brightness: ^0.2.0
  flutter_meedu: ^8.0.0+1
  flutter_spinkit: ^5.1.0
  meta: ^1.7.0
  dart_vlc: ^0.4.0
    # git:
    #   url: https://github.com/alexmercerind/dart_vlc.git
    #   ref: master
  

  window_manager: ^0.2.0
  hotkey_manager: ^0.1.6
  wakelock: ^0.6.1+2
  shared_preferences: ^2.0.13
  helpers: ^1.1.4
  dio: ^4.0.4
  dio_smart_retry: ^1.2.0
  path_provider: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.zezo357.flutter_meedu_videoplayer
        pluginClass: FlutterMeeduVideoplayerPlugin
      ios:
        pluginClass: FlutterMeeduVideoplayerPlugin
      windows:
        pluginClass: FlutterMeeduVideoplayerPlugin

      #web:
        #pluginClass: FlutterMeeduVideoplayerWeb
        #fileName: flutter_meedu_videoplayer_web.dart
  assets:
    - assets/icons/fast-forward.png
    - assets/icons/fullscreen.png
    - assets/icons/minimize.png
    - assets/icons/mute.png
    - assets/icons/play.png
    - assets/icons/pause.png
    - assets/icons/repeat.png
    - assets/icons/rewind.png
    - assets/icons/sound.png
    - assets/icons/picture-in-picture.png
    - assets/icons/fit.png
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
